[project]
name = 'contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.campaigns]
path = 'contracts/campaigns.clar'
clarity_version = 3
epoch = 3.1

[contracts.mock-sbtc]
path = 'contracts/mock-sbtc.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
